server:
  port: 8088


spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl.lpb.lv.net
    username: C##minhlv
    password: 12345678
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#spring.application.name=microservice-demo

