server:
  port: 8081
spring:
  application:
    name: job-service
  datasource:
    url: jdbc:mysql://192.168.31.108:3306/job_service?createDatabaseIfNotExist=true
    username: root
    password: Abc123456789@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.182:8761/eureka
    register-with-eureka: false
    fetch-registry: true
