global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order_service:8080']
  - job_name: 'payment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment_service:8082']
  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory_service:8083']
  - job_name: 'job_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['job_service:8081']
