version: '3.8'

services:
  authen-service:
    build: .
    image: authen-service:latest
    container_name: authen-service
    ports:
      - "8888:8888"
    networks:
      - microservice_system
networks:
  microservice_system:
    external: true
